export const productData = [
    {
        id:1,
        title:"Inverter Power Generator",
        thumbnail:'/images/product/01.png',
        price:"1099",
        discount_price:"999",
    },
    {
        id:2,
        title:"Compact Drill Cordless",
        thumbnail:'/images/product/02.png',
        price:"259",
        discount_price:"199",
    },
    {
        id:3,
        title:"LiIon Compact Drill Driver",
        thumbnail:'/images/product/03.png',
        price:"299",
        discount_price:"198",
    },
    {
        id:4,
        title:"Compound Saw Makita",
        thumbnail:'/images/product/04.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:5,
        title:"LiIon Compact Drill Driver",
        thumbnail:'/images/product/01.png',
        price:"299",
        discount_price:"198",
    },
    {
        id:6,
        title:"Compound Saw Makita",
        thumbnail:'/images/product/02.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:7,
        title:"Inverter Power Generator",
        thumbnail:'/images/product/01.png',
        price:"1099",
        discount_price:"999",
    },
    {
        id:8,
        title:"Compact Drill Cordless",
        thumbnail:'/images/product/02.png',
        price:"259",
        discount_price:"199",
    },
    {
        id:9,
        title:"LiIon Compact Drill Driver",
        thumbnail:'/images/product/03.png',
        price:"299",
        discount_price:"198",
    },
    {
        id:10,
        title:"Compound Saw Makita",
        thumbnail:'/images/product/04.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:11,
        title:"LiIon Compact Drill Driver",
        thumbnail:'/images/product/01.png',
        price:"299",
        discount_price:"198",
    },
    {
        id:12,
        title:"Compound Saw Makita",
        thumbnail:'/images/product/02.png',
        price:"459",
        discount_price:"358",
    },
]